apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: ssibrahimbas.com/persistent-mongo/car
      context: car
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**'
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*